- name: Run docker sentry celery container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    command: "{{ docker_sentry_celery_command }}"
    env: "{{ docker_sentry_celery_env }}"
    expose: "{{ docker_sentry_celery_expose }}"
    hostname: "{{ docker_sentry_celery_hostname }}"
    image: "{{ docker_sentry_celery_image }}"
    links: "{{ docker_sentry_celery_links }}"
    name: "{{ docker_sentry_celery_name }}_{{ item }}"
    net: "{{ docker_sentry_celery_net }}"
    ports: "{{ docker_sentry_celery_ports }}"
    memory_limit: "{{ docker_sentry_memory_limit }}"
    log_driver: "{{ docker_sentry_log_driver }}"
    log_opt: "{{ docker_sentry_log_opt }}"
    pull: always
    restart_policy: always
    state: reloaded
    tty: yes
    volumes: "{{ docker_sentry_celery_volumes }}"
    volumes_from: "{{ docker_sentry_celery_volumes_from }}"
  with_sequence: count={{ docker_sentry_celery_instances }}
  when: docker_sentry_celery_instances > 0
  tags:
    - install
    - upgrade
    - restart
