- include: celery.yml
  vars:
    docker_sentry_celery_instances: "{{ docker_sentry_celery_beat_instances }}"
    docker_sentry_celery_name: "{{ docker_sentry_celery_beat_name }}"
    docker_sentry_celery_image: "{{ docker_sentry_celery_beat_image }}"
    docker_sentry_celery_command: "{{ docker_sentry_celery_beat_command }}"
    docker_sentry_celery_data_dir: "{{ docker_sentry_celery_beat_data_dir }}"
    docker_sentry_celery_env: "{{ docker_sentry_celery_beat_env }}"
    docker_sentry_celery_net: "{{ docker_sentry_celery_beat_net }}"
    docker_sentry_celery_hostname: "{{ docker_sentry_celery_beat_hostname }}"
    docker_sentry_celery_expose: "{{ docker_sentry_celery_beat_expose }}"
    docker_sentry_celery_ports: "{{ docker_sentry_celery_beat_ports }}"
    docker_sentry_celery_links: "{{ docker_sentry_celery_beat_links }}"
    docker_sentry_celery_volumes: "{{ docker_sentry_celery_beat_volumes }}"
    docker_sentry_celery_volumes_from: "{{ docker_sentry_celery_beat_volumes_from }}"
  when: docker_sentry_celery_beat
  tags: [sentry]

- include: celery.yml
  vars:
    docker_sentry_celery_instances: "{{ docker_sentry_celery_worker_instances }}"
    docker_sentry_celery_name: "{{ docker_sentry_celery_worker_name }}"
    docker_sentry_celery_image: "{{ docker_sentry_celery_worker_image }}"
    docker_sentry_celery_command: "{{ docker_sentry_celery_worker_command }}"
    docker_sentry_celery_env: "{{ docker_sentry_celery_worker_env }}"
    docker_sentry_celery_net: "{{ docker_sentry_celery_worker_net }}"
    docker_sentry_celery_hostname: "{{ docker_sentry_celery_worker_hostname }}"
    docker_sentry_celery_expose: "{{ docker_sentry_celery_worker_expose }}"
    docker_sentry_celery_ports: "{{ docker_sentry_celery_worker_ports }}"
    docker_sentry_celery_links: "{{ docker_sentry_celery_worker_links }}"
    docker_sentry_celery_volumes: "{{ docker_sentry_celery_worker_volumes }}"
    docker_sentry_celery_volumes_from: "{{ docker_sentry_celery_worker_volumes_from }}"
  when: docker_sentry_celery_worker
  tags: [sentry]

- include: server.yml
  when: docker_sentry_server
  tags: [sentry]
