- name: Ensure docker sentry server directories exist
  become: true
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_sentry_server_data_dir }}"
    - "{{ docker_sentry_conf_dir }}"
  tags:
    - install
    - settings

- name: Copy docker sentry sentry.conf.py.j2 file
  become: true
  template:
    src: "{{ docker_sentry_source_conf }}"
    dest: "{{ docker_sentry_conf_file }}"
    mode: 0644
  tags:
    - install
    - settings

- name: Run docker sentry server container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    command: "{{ docker_sentry_server_command }}"
    env: "{{ docker_sentry_server_env }}"
    expose: "{{ docker_sentry_server_expose }}"
    hostname: "{{ docker_sentry_server_hostname }}"
    image: "{{ docker_sentry_server_image }}"
    links: "{{ docker_sentry_server_links }}"
    name: "{{ docker_sentry_server_name }}"
    net: "{{ docker_sentry_server_net }}"
    ports: "{{ docker_sentry_server_ports }}"
    memory_limit: "{{ docker_sentry_memory_limit }}"
    log_driver: "{{ docker_sentry_log_driver }}"
    log_opt: "{{ docker_sentry_log_opt }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_sentry_server_volumes }}"
    volumes_from: "{{ docker_sentry_server_volumes_from }}"
  tags:
    - install
    - upgrade